name = "social-app"
version = "0.1.0"

[contracts]
social-app = "social-app.clar"

[devnet]
[[devnet.accounts]]
name = "deployer"
balance = 1000000000000000

[[devnet.accounts]]
name = "user1"
balance = 1000000000000000

[[devnet.accounts]]
name = "user2"
balance = 1000000000000000